- src: https://github.com/geerlingguy/ansible-role-repo-epel
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/forge_users.git
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/admin_node.git
