- src: https://github.com/geerlingguy/ansible-role-repo-epel
  path: roles/
  name: ansible-role-repo-epel

- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/forge_users.git
  path: roles/
  name: forge_users
